{% set name = "pyspellchecker" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 764dfe1bcbd4d860b74205402167d55a02910870c07b83678e7d6b5a4d471909

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - spellchecker

about:
  home: https://github.com/barrust/pyspellchecker
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure python spell checker based on work by Peter Norvig

extra:
  recipe-maintainers:
    - dschreij
    - smathot
