{% set name = "pyspellchecker" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4b0638bee1eff346b60172a9b508ac952a9eafc4fbf909474fc9bc7f16df09f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >= 3.6
  run:
    - python >= 3.6

test:
  imports:
    - spellchecker

about:
  home: https://github.com/barrust/pyspellchecker
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure python spell checker based on work by Peter Norvig

extra:
  recipe-maintainers:
    - dschreij
    - smathot
